### ISSUE TITLE
FOVAdditional causes crash on first level?

### ISSUE THREAD

**Issue by emoose** [nipkownix/re4_tweaks#4] opened 2021-10-22 14:11 UTC
Hi, seems re4_tweaks causes a crash for me on the first level for some reason, I wrote some more about it on the NM page: https://www.nexusmods.com/residentevil4/mods/101?tab=posts

>Some reason I keep running into a crash right at the start of the game though, after starting new game skip through the intro movies, then when you spawn in the map just run forward, always seems to crash for me just before reaching the signpost :/

>Strange thing is I'm sure I got passed the signpost before, with the exact same settings etc. Not sure what could have changed that made it start crashing...

>If I rename winmm.dll to disable it the crashing goes away, so seems it's probably something that re4_tweaks added in. (should probably mention, I'm using the re4hd pack too)

>E: ah might be caused by FOVAdditional, I was using 20 for the above, but changing it to 0 seems to get rid of the crashing.
Unfortunately the FOV changes is mostly what I used re4_tweaks for though... I could use a save to skip past the area that crashes & use 20 with that, but not sure if there's still a chance of something else also crashing later on due to it :/

EDIT: seems it's not just the first level, have had crashes loading from saves too :/ changing back to FOVAdditional = 0 stops the crashes from happening though.

**Comment by emoose** [comment] 2021-10-25 00:37
Aha think I found the fix for it! The game allocs some vertex buffers at 0x939DD0 (and around 0x94BC10), but seems they're too small, making IDirect3DVertexBuffer9::Lock return E_FAIL when the game tries locking an offset past the size of one of those buffers (it fails at ~0x5bbe40, while one of the buffers is size 0x5B8D80)

Just hex edited the EXE to double the buffer sizes, and with that the crashes seem to be gone :)

I'll update this with a list of file offsets in a sec, if you want to add this to your mod feel free btw!

**Comment by nipkownix** [comment] 2021-11-29 21:57
Reopening this because some people on nexus reported an issue with RaiseInventoryAlloc.

Some items in the inventory screen are just invisible when RaiseInventoryAlloc is enabled:

![image](https://user-images.githubusercontent.com/33870163/143948989-fd466650-a8dd-4025-a13d-9b366d09b464.png)

>So I uninstalled the HD project so it's just the vanilla game with this mod and it's all good.  There seems to be a conflict with the HD project that makes some of the inventory textures missing. 

Doesn't look like it happens without the HD project.

I downloaded the older public version of the HD project to test, but I cant reproduce the issue.

 Do you have any idea about what could be causing this, @emoose ?

**Comment by emoose** [comment] 2021-11-29 22:39
Huh that's weird, can't really think of what might be causing that... do you know if the user has 4GB patch applied to their EXE?

I never saw anything like that in my playthrough with HD project + RaiseInventoryAlloc, but that was near end of the game so didn't really try it for too long, if the user can post a save with that issue somewhere it could help.

**Comment by nipkownix** [comment] 2021-11-29 23:46
I tried using the 4GB patch, but that changed nothing here.
I asked them if they have it applied, and also for a save file.

Pretty weird, though. You'd think all the items would be invisible if there was an issue when loading ss_pzzl or something like that.

**Comment by nipkownix** [comment] 2021-12-03 12:36
Guess what? With your build from #25, I'm able to reproduce the issue:

![image](https://user-images.githubusercontent.com/33870163/144603493-1e58d924-9ebb-4c37-b2e2-a94f9d833231.png)

My game is set to 144 fps.

Could it be something related to fps, then? The issue is gone with RaiseInventoryAlloc off, for some reason. Very intriguing.

**Comment by emoose** [comment] 2021-12-03 23:28
Hmm, did a test of adding another buffer between g_MemPool_SubScreen & g_MemPool_SubScreen2, so it's
```C
uint8_t g_MemPool_SubScreen[0x4000000];
uint8_t g_MemPool_SubScreen_SafetyBuf[0x4000000];
uint8_t g_MemPool_SubScreen2[0x4000000];
```
Then used VirtualProtect to set that safetybuf as read-only, and seems it's trying to get written when inventory is opened, I think it's the MemorySwap call at 0x768113 (1.1.0) that's trying to write to it, but haven't found out why yet.

**Comment by nipkownix** [comment] 2021-12-09 13:03
Looks like the issue still shows up for the Nexus guy. Strange.

Well, maybe the problem is elsewhere.

There is another limitation with this game regarding poly count. If the limit is reached, some models just become invisible. I've never seen this happen in the inventory screen, though..
Albert mentioned it earlier and said he reached this limit on some cutscenes.
Maybe it is the same issue?

Here's how to reproduce it:

Download the files from here:
https://www.dropbox.com/sh/v8xi4zck39l5cyg/AAAZ7xlJ3_D6O69nlKO0BKLDa?dl=0

put both pack.lfs file inside the ImagePackHD folder, and the udas.lfs file inside the Em folder.

Go to the movie browser and watch this cutscene:
![image](https://user-images.githubusercontent.com/33870163/145401162-5b689e93-783a-4e09-935e-b333324158df.png)

Leon should become invisible a couple of seconds into the cutscene.

Maybe the reason the inventory issue is so inconsistent to reproduce is because the stage you're in also contributes to filling up this limit.. not sure.

**Comment by nipkownix** [comment] 2021-12-10 22:12
Figured out the issue with the invisible model in the cutscene above, and pushed a fix. Not sure if it fixes the inventory issue, though. Even if it doesn't, I'm guessing it should be a similar problem? ~It would be a lot easier if we could just reliably see the issue :/~

**Closed** 2022-01-12 20:04 UTC
