### ISSUE TITLE
Game crash when select Bowgun

### ISSUE THREAD

**Issue by JackSound01** [nipkownix/re4_tweaks#309] opened 2022-08-07 22:42 UTC
### Validation

- [x] Game has been updated to the latest RE4HD release (v1.1: https://www.re4hd.com/?p=9552)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.1 SFV: [BIO4-HDProject1.1-SFV.zip](https://github.com/emoose/re4-research/files/9207370/BIO4-HDProject1.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

In assignment ada when you select the bowgun, the game instantly crash.

**Comment by nipkownix** [comment] 2022-08-07 22:59
Could you please create a folder called "CrashDumps" inside Bin32, and then try to make the game crash again? A zip will be created with info that might help us find the cause of the crash.

**Comment by JackSound01** [comment] 2022-08-07 23:14
> Could you please create a folder called "CrashDumps" inside Bin32, and then try to make the game crash again? A zip will be created with info that might help us find the cause of the crash.

There is it https://www.mediafire.com/file/7s8wu9vvetcouxw/bio4.exe.20220807201204.zip/file

**Comment by nipkownix** [comment] 2022-08-08 00:11
It is crashing when reading stuff related to a model (probably the bowgun's model, as you mentioned). Doesn't seem to be caused by re4_tweaks. Seems to be something corrupted in your game. Are you using the HD Project? If not, you could try to verify the integrity of the game files on Steam.

**Comment by JackSound01** [comment] 2022-08-08 00:24
> It is crashing when reading stuff related to a model (probably the bowgun's model, as you mentioned). Doesn't seem to be caused by re4_tweaks. Seems to be something corrupted in your game. Are you using the HD Project? If not, you could try to verify the integrity of the game files on Steam.

I'm using the last version of Hd Project 1.1 and the last of tweaks.

**Comment by emoose** [comment] 2022-08-08 01:30
Definitely something related to the bowgun/wep50 model, could you try checking with the bio4.sfv to make sure your HDProject data is all valid? A guide is at https://www.re4hd.com/?p=9454 ("The game won’t open or there are some fatal crashes (I)" section)

Besides that I did notice you're playing at 3840x2160, wonder if that could be causing some issue with memory maybe, could be worth testing if a lower resolution stops the crash at all.

**Comment by JackSound01** [comment] 2022-08-08 01:52
> Definitely something related to the bowgun/wep50 model, could you try checking with the bio4.sfv to make sure your HDProject data is all valid? A guide is at https://www.re4hd.com/?p=9454 ("The game won’t open or there are some fatal crashes (I)" section), you should have a bio4.sfv included with HDProject 1.1, otherwise you can grab it from here: https://github.com/emoose/re4-research/files/9207370/BIO4-HDProject1.1-SFV.zip
> 
> Besides that I did notice you're playing at 3840x2160, wonder if that could be causing some issue with memory maybe, could be worth testing if a lower resolution stops the crash at all.

I try at 1080p but the crash goes on, and with sfv i have more than 300 errors, this thing i have it since a long time ago

**Comment by albertre4HD** [comment] 2022-08-08 08:25
Did you change Ada's costume using re4_tweaks?
Ada's Spy costume isn't compatible with some Separate Ways weapons, and RE2 costume has some glitches.

**Comment by JackSound01** [comment] 2022-08-08 11:38
> Did you change Ada's costume using re4_tweaks? Ada's Spy costume isn't compatible with some Separate Ways weapons, and RE2 costume has some glitches.

Yes man, i'm using the spy costume. Later at my home i'll try.

**Comment by albertre4HD** [comment] 2022-08-08 11:43
Ahh, then that's the problem. Spy costume doesn't have the data for certain weapons. Different costumes have different weapon compatibility, Since Separate Ways model was created when the PS2 port was created, they didn't bother to make the other Ada costumes compatible with the new weapons.

Not sure if this can be fixed somehow... Maybe I can port some data from Ada's SW costume model to the other 2 Ada's models...

**Comment by nipkownix** [comment] 2022-08-08 13:34
> Not sure if this can be fixed somehow... 
I think I figured out a workaround for this issue.
Albert, do you happen to know of more weapons that cause crashes?

**Comment by albertre4HD** [comment] 2022-08-08 14:26
Yes, the inventory character model simply disappears when a "conflicting" weapon is equipped when using Raz0r trainer, So, that's a good fix.
There were a lot of weapons that were not compatible with other characters, but right now only the costume can be changed, not the player, so, only the Ada's weapons should be fixed right now:

RE2 Ada: Chicago Typewriter = CRASH
RE2 Ada: Shotgun = Bugged hand texture
RE2 Ada: Bow gun = OK

Spy Ada: Chicago Typewriter= Bugged hand texture
Spy Ada: Shotgun = Bugged hand texture
Spy Ada: Bow gun = CRASH

**Comment by nipkownix** [comment] 2022-08-08 15:52
Thank you, Albert!

I've got a better workaround than Raz0r's. 
When unsupported weapons are equipped, the game displays the "empty hand" player instead of it just being invisible:

![image](https://user-images.githubusercontent.com/33870163/183459577-744b5f4e-230f-4180-b321-406ee4599efa.png)

Looking pretty good so far, but I've only added the Bowgun to the blacklist. Will add the Typewriter now and provide a test build soon.

The ones that show bugged hand textures should be fine to leave as is, I believe? IMO it isn't that big of a deal.

**Comment by albertre4HD** [comment] 2022-08-08 16:18
Agree! This looks ok! And the hands are not a problem if it doesn't make the game to crash.

Even some hands' textures will be wrong ingame when equipping these weapons, it's not an inventory exclusive bug.
But it's strange, it's different compared to the inventory. Sometimes when Ada equips a weapon, the hands will be wrong in the inventory, but they will be ok ingame, and sometimes only one hand will be wrong... 

Raz0r trainer has an option called "weapon fix". It simply removes the character completely in the inventory, no matter the weapon you equipped.

**Comment by JackSound01** [comment] 2022-08-08 16:49
So.. what's the fix? by the way, i can't use the Raz0r trainer.

**Comment by nipkownix** [comment] 2022-08-08 16:57
@JackSound01 @albertre4HD Could you test if this build solves the crashes?
[dinput8.zip](https://github.com/nipkownix/re4_tweaks/files/9283656/dinput8.zip)

**Comment by albertre4HD** [comment] 2022-08-08 17:02
Good!
It works here (HD project 1.1) for both RE2 Ada: Chicago Typewriter  & Spy Ada: Bow gun.
It loads her "no-weapon" animation ;D

**Comment by JackSound01** [comment] 2022-08-08 17:22
> @JackSound01 @albertre4HD Could you test if this build solves the crashes? [dinput8.zip](https://github.com/nipkownix/re4_tweaks/files/9283656/dinput8.zip)

Works good, thank you... It's a shame that the weapon doesn't appear, maybe a next thing for tweaks or hd project for the future.

**Closed** 2022-08-08 18:22 UTC
Labels: bug
