### ISSUE TITLE
Keyboard controls for doing backflips with the escape boat

### ISSUE THREAD

**Issue by RiasatSalminSami** [nipkownix/re4_tweaks#158] opened 2022-04-01 13:32 UTC
### Describe the feature you'd like to see added

So far I've been trying various keyboard button combinations to see if I can flip the boat, but nothing worked. As far as I know, it's possible to do it with gamepad on GC and Wii port. Can't test gamepad on PC right now since I don't have one.

I've been trying to find some answers regarding this, but there isn't any documentation for this. This was the only lead: https://steamcommunity.com/app/254700/discussions/0/627456487064225218/  and even there, no one managed to find anything.

I think, just like the lack of controls to flip the items in your inventory, you cant flip the boat with keyboard by default.

**Comment by emoose** [comment] 2022-04-02 01:56
Only been able to find button-press checks inside `pl0ePathMove` so far, looks like that's only looking for `KEY_LEFT/KEY_RIGHT/KEY_FORWARD/KEY_BACK`, haven't found any other code related to jet-ski that checks buttons.

If anyone with gamepad could test if the combo in that steam link works or not it'd be appreciated, seems like it might have been stripped out entirely.

**Comment by linkthehylian** [comment] 2022-04-03 15:45
I remember trying to do this several times with keyboard and it never ended up working. I thought I was just doing it wrong but it looks like it might have actually never been properly implemented. All the times I've tried with a controller have worked just fine though, so I think it's safe to assume that it only recognizes that kind of input to be activated.

**Comment by emoose** [comment] 2022-04-03 21:09
Ahh right, thought I was probably mistaken about it being taken out.

Just had another look and seems `pl0e_R1_Jump` does have a `(Joy[0].buttonStates0_14 & JOY_RT) != 0 && sub_401528(1, 0x80)` check inside it, not sure how I missed that before 😅 

I'm not certain but maybe the `Joy[0].buttonStates` field is only set from gamepad, and doesn't get updated from keyboard at all, not sure though. 

Or maybe it's the sub_401528 call there which is stopping it from working, I'm not really sure what that sub checks for (GC/PS2/VR don't have that call at all), will try looking into that some more.

**Comment by linkthehylian** [comment] 2022-04-05 04:06
I had to play a bit to get to where you wanted. It should be save number seventeen. @emoose 
[savegame00.zip](https://github.com/nipkownix/re4_tweaks/files/8414731/savegame00.zip)

**Comment by emoose** [comment] 2022-04-05 06:21
> I had to play a bit to get to where you wanted. It should be save number seventeen. @emoose [savegame00.zip](https://github.com/nipkownix/re4_tweaks/files/8414731/savegame00.zip)

Many thanks! So confirmed that part of the code `(Joy[0].buttonStates0_14 & JOY_RT) != 0 && sub_401528(1, 0x80)` does seem responsible, patching it to skip those checks makes it always do a trick when you jump (either roll forward or barrel-roll, either random or depends on which part of the ramp you jump from?)

Now it's just a matter of hooking that code and letting it also check a key combo, I guess LMB+RMB should be a good default for that.

**Comment by nipkownix** [comment] 2022-04-13 18:12
Latest release has the PR above merged. Many thanks, @emoose!

**Closed by nipkownix** 2022-04-13 18:12 UTC
