### ISSUE TITLE
Controller going crazy

### ISSUE THREAD

**Issue by Nitsug72** [nipkownix/re4_tweaks#362] opened 2022-11-12 12:20 UTC
### Validation

- [X] Game has been updated to the latest RE4HD release (v1.1: https://www.re4hd.com/?p=9552)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.1 SFV: [BIO4-HDProject1.1-SFV.zip](https://github.com/emoose/re4-research/files/9207370/BIO4-HDProject1.1-SFV.zip))

### Describe your issue here (drag+drop ZIP to attach it)

[Video example](https://www.youtube.com/watch?v=77wRdCZrprg)
Game version:  1.1.0
Re4_tweaks ver: 1.7.7.6

Hi. I'm not really sure if this is re4_tweaks' fault but so far it has never happened with any other game.

Seemingly at random the controller (DS4) stops working properly and the game shows keyboard prompts in the inventory menu.

It happens even if:
-I disable steam input
-I connect the controller through USB instead of bluetooth
-I use a virtual x360 controller (with DS4windows) either through USB or bluetooth
-I set input.ini as read only so the game can't modify it (I thought it could help)

I don't remember this ever happening before and I've been using the hd project since february.

**Comment by LethalPlacebo** [comment] 2022-11-12 16:58
This doesn't seem related to the HD Project or RE4 Tweaks, but I'll recommend you try this anyway: 

-Go to "Device Manager" on your PC
-Open the "Sound, video and game controllers tab"
-Your DS4 should be listed near the bottom as simply "wireless controller"
-Completely uninstall and remove it, then unplug and replug your DS4 and see if it works with RE4.

You can also test the controller at a system level:

-Open "Control Panel" on your PC
-Open "Hardware and Sound"
-Open "Devices and Printers"
-Once again you should see "wireless controller" here. Right-click it and open "game controller settings" then click "advanced." Windows will show you a screen that lets you test out all buttons and analog inputs.

**Comment by Nitsug72** [comment] 2022-11-12 18:02
It does work for like 5-15 minutes and _then_ it starts having this issue. I'm pretty sure it's not the controller, no other game has any similar issue.

**Comment by LethalPlacebo** [comment] 2022-11-12 20:24
> It does work for like 5-15 minutes and _then_ it starts having this issue. I'm pretty sure it's not the controller, no other game has any similar issue.

So it still has this issue after trying the steps above, right? No other USB controller devices are plugged in?

**Comment by Nitsug72** [comment] 2022-11-12 20:32
Yup, no other controller connected.

**Comment by Nitsug72** [comment] 2022-11-12 20:34
As I said before, RE4 is the only game with this problem.

**Comment by LethalPlacebo** [comment] 2022-11-12 20:41
I see. You said you've set input.ini as read-only, have you tried outright deleting it?

**Comment by Nitsug72** [comment] 2022-11-12 21:00
Just tried that, still happens. I did notice that if I hold the right stick in any direction the controller behaves "normally" (as shown in the video). Could it be related to stick drifting? I'll try to unbind the right stick on steam input to see if something changes @_@

**Comment by Nitsug72** [comment] 2022-11-12 21:09
I had the same issue but I had to hold the left stick instead.

**Comment by LethalPlacebo** [comment] 2022-11-12 21:17
Hmmm. Try to make sure the gyro in the DS4 also isn't bound to anything?

**Comment by Nitsug72** [comment] 2022-11-12 21:24
It isn't.

> Hmmm. Try to make sure the gyro in the DS4 also isn't bound to anything?

**Comment by nipkownix** [comment] 2022-11-12 21:28
Sounds like this issue:
https://steamcommunity.com/app/254700/discussions/0/2954915322314982947/

I've seen some people report that before, even before I made re4_tweaks, so I don't think it is caused by it. Unless some change we're making is triggering the same bug, which _could_ happen. Could you test without re4_tweaks?

**Comment by Nitsug72** [comment] 2022-11-12 21:33
> Sounds like this issue: https://steamcommunity.com/app/254700/discussions/0/2954915322314982947/
> 
> I've seen some people report that before, even before I made re4_tweaks, so I don't think it is caused by it. Unless some change we're making is triggering the same bug, which _could_ happen. Could you test without re4_tweaks?

Could be the same. I'll try to disable steam overlay and if that doesn't work I'll run the game without re4_tweaks.

**Comment by Nitsug72** [comment] 2022-11-12 22:01
> Could be the same. I'll try to disable steam overlay and if that doesn't work I'll run the game without re4_tweaks.
Still happens. In fact, it happens from the very beginning without re4_tweaks, which leads me to believe that this is somehow performance-related (also, the main menu animation looks "choppy" when I have this problem). Mi pc is very weak and I need to disable v-sync to get a stable framerate.

The thing is, I've been playing since february and this started happening just recently.

**Comment by nipkownix** [comment] 2022-11-13 12:41
Hmm, yeah.. odd. It would be great if we could figure out a way to reproduce the issue here, so I could take a look, but this just never happened to me ever since this port released :/

**Comment by Nitsug72** [comment] 2022-11-17 00:25
Hi. I tested a virtual x360 gamepad (with DS4windows) with the "Hide DS4" option enabled and the same happens. I also tried to play on the least "cpu intensive" enviroments and managed to play for longer before this started happening. Now I'm pretty sure it's something performance-related and not the controller's fault.
Just wanted to mention that.

**Comment by emoose** [comment] 2022-11-17 01:47
If you are getting performance problems/framedrops I'd guess that could have an effect on input, don't really know why it'd stop working completely though.

Maybe worth trying out dxvk or #255, I've heard dxvk can help with framedrops a lot at least.
IIRC setting up dxvk just needs the x32 d3d9.dll/dxgi.dll from tar.gz at https://github.com/doitsujin/dxvk/releases/tag/v2.0 extracted next to the game EXE (dxvk 2.0 did change Vulkan requirements though, so you might also want to try the earlier https://github.com/doitsujin/dxvk/releases/tag/v1.10.3 version as well, could perform better than 2.0 for you)

If you try those let us know if there's any effect, otherwise maybe will look into adding some debug info around the controller related code, to get some idea why game is deciding to stop reading from controller.

**Comment by Nitsug72** [comment] 2022-11-17 14:13
I'll try, though I think the links in #255 don't work anymore.


> E: btw after the controller stops working in the game, do you know if other things are still able to recognize it? eg Win10/Win11 start menu should respond to LS if it's still recognized by the OS, if that also doesn't respond maybe it's not entirely game related...

Yeah, it works just fine with everything.

**Comment by emoose** [comment] 2022-11-19 19:04
Ah, done a rebase + rebuild of #255, build can be found at https://github.com/nipkownix/re4_tweaks/suites/9400765838/artifacts/443597531
It could also be worth trying the re4_tweaks+dxvk combined DLL at https://github.com/nipkownix/re4_tweaks/issues/361#issuecomment-1320304805 too.

Hoping one of these methods can help with it somewhat, will also look into adding that debugging stuff to figure out why it happens soon.

**Comment by Nitsug72** [comment] 2022-11-20 09:09
Hi. A little update on my situation.
Aparently this doesn't happen if I disable bluetooth and connect the controller through USB. So I have two theories:
-This actually _is_ caused by poor performance and my pc is so weak that enabling bluetooth has a meaningful impact.
-It's related to using a DS4 through bluetooth (though no other game ever had this issue, at least for me)

**Comment by Nitsug72** [comment] 2022-11-20 09:10
> Ah, done a rebase + rebuild of #255 (E: was merged into master too, can get that from https://github.com/nipkownix/re4_tweaks/suites/9401866481/artifacts/443673397)
> 
> It could also be worth trying the re4_tweaks+dxvk combined DLL at [#361 (comment)](https://github.com/nipkownix/re4_tweaks/issues/361#issuecomment-1320304805) too.
> 
> Hoping one of these methods can help with it somewhat, will also look into adding that debugging stuff to figure out why it happens soon.

I'll try. thanks <3

**Comment by LethalPlacebo** [comment] 2022-11-20 09:20
> Hi. A little update on my situation. Aparently this doesn't happen if I disable bluetooth and connect the controller through USB. So I have two theories: -This actually _is_ caused by poor performance and my pc is so weak that enabling bluetooth has a meaningful impact. -It's related to using a DS4 through bluetooth (though no other game ever had this issue, at least for me)

I thought you said you already tried with your controller wired? Or had you not disabled Bluetooth when trying it wired before? 

Anyway, your Bluetooth is most likely the problem here, but probably not because your PC is weak. When I try to play RE4 on my PC when a Bluetooth driver is installed, I get a stutter every 5 seconds or so. I should have tried disabling it first, but decided to just uninstall it altogether, and the problem immediately went away.

Similarly to your problem, no other game had stutters when I had the Bluetooth driver installed, but if I used a controller with Bluetooth and then the controller lost sync, it would tank my performance because the Bluetooth driver would freak out.

Anyway RE4 seems to really not like Bluetooth devices lol.

**Comment by Nitsug72** [comment] 2022-11-20 09:24
I did, but I still had my headphones connected.

**Comment by Nitsug72** [comment] 2022-11-20 10:35
> Ah, done a rebase + rebuild of #255 (E: was merged into master too, can get that from https://github.com/nipkownix/re4_tweaks/suites/9401866481/artifacts/443673397)

That one definitively helped! I played through the first chapter with no slowdowns at all (only two minor ones in particule-intense cutscenes) It felt way smoother than before.

**Comment by Nitsug72** [comment] 2022-11-20 10:52
I'm yet to try dxvk. I'll keep you informed once I do.

**Comment by Nitsug72** [comment] 2022-11-21 01:17
I tried both #255 and dxvk [v1.10.3] at the same time. I'm in 1-3 right now, so far the game ran _almost_ flawlessly aside from some stutter here and there.
![aaa](https://user-images.githubusercontent.com/71330403/202938361-2fc41cd7-7a2a-477f-8817-840611ae8588.PNG)

**Comment by emoose** [comment] 2022-11-21 23:12
Huh interesting, guess maybe game is reading from both wired & bluetooth, maybe the stutter interferes with something with the bluetooth controller, and game ends up disconnecting from both because of it (just a guess, but the gamepad code in here is pretty bad, so wouldn't be surprised if one controller disconnecting would break all of them...)

I wonder if `PrecacheModels` might help with your stutter issue at all, that should ensure all the models in the stage are loaded in, so should reduce slowdowns as you play hopefully. (we could probably make that default really, or at least enable it in HDProject.ini, since there are some stutters there that can be fixed by it: https://github.com/nipkownix/re4_tweaks/issues/274 - I think only downside with it is maybe more increased VRAM usage, but haven't confirmed that myself)

**Comment by Nitsug72** [comment] 2022-11-21 23:50
[Here's another video.](https://youtu.be/Vd10FvFYpl0) 
I

**Comment by Nitsug72** [comment] 2022-11-21 23:51
Sorry I don't know what I just did @_@

**Comment by Nitsug72** [comment] 2022-11-30 07:59
I think I found the cuprit. [These](https://www.akg.com/Headphones/Over-ear%20%26%20On-ear/AKG+Y500+Wireless.html) are the headphones I'm using (and have been since I got a BT adapter for my pc)

![culprit](https://user-images.githubusercontent.com/71330403/204739343-b3e7592e-3162-4628-97a0-8611a641696d.PNG)

This device has a weird motion sensor that pauses/resumes whatever you're playing when you take it off (and is annoying as hell because it doesn't work properly)
I'm not a very technical person, but my guess is that the game is recognizing the headphones as a input device. I managed to _consistently_ trigger this bug by taking them off .-.

**Comment by Nitsug72** [comment] 2022-11-30 08:06
Update: I just tested the game with no controller connected (just keyborad/mouse). It still happens.
It's the headphones. Mystery solved.

**Comment by Nitsug72** [comment] 2022-11-30 08:20
I have just found out after three years that there is a way to disable this godforsaken feature. At last, I am allowed to play.

**Comment by Nitsug72** [comment] 2022-11-30 08:32
Tested the game again with the auto-pause/play thing disabled and the game worked just fine.

Guess what? Pressing the little play/pause button on the headphones triggers this bug as well.

I assume it could happen with almost any audio device. I'm so glad that I finally figured this out. Thanks a lot for your time and effort, I hope this thread becomes useful for other people going through the same problem.

**Closed** 2022-12-02 14:53 UTC
Labels: bug
